language: python

python: 
  - 3.6

services:
  - mysql

env:
  - DJANGO=1.11.2 DB=mysql

before_install:
  - export DJANGO_SETTINGS_MODULE=dj_comps.settings
  - export PIP_USE_MIRRORS=true
  - export BUILD_ON_TRAVIS=true

install:
  - pip install -r requirements.txt

before_script:
  - mysql -e 'create database db;'
  - python3 manage.py makemigrations
  - python3 manage.py migrate

script:
  - flake8
  - python3 manage.py test